import { initializeApp } from "https://www.gstatic.com/firebasejs/12.0.0/firebase-app.js";
import { getAuth, signInWithEmailAndPassword, onAuthStateChanged, signOut } from "https://www.gstatic.com/firebasejs/12.0.0/firebase-auth.js";
import { getFirestore, collection, getDocs, addDoc, updateDoc, deleteDoc, doc, query, orderBy, limit } from "https://www.gstatic.com/firebasejs/12.0.0/firebase-firestore.js";
import { getStorage, ref, uploadBytes, getDownloadURL } from "https://www.gstatic.com/firebasejs/12.0.0/firebase-storage.js";
import { firebaseConfig } from "./firebase-config.js";
const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app),storage=getStorage(app);let products=[],editingId=null,oldImage='';const $=id=>document.getElementById(id),money=n=>'₹'+Number(n||0).toLocaleString('en-IN');
function showLogin(){$('login').classList.add('show');$('dashboard').style.display='none'}function showDashboard(){$('login').classList.remove('show');$('dashboard').style.display='block'}
window.login=async()=>{ $('loginError').textContent='';try{await signInWithEmailAndPassword(auth,$('email').value.trim(),$('password').value)}catch(e){$('loginError').textContent='Login failed: '+e.message}};window.logout=()=>signOut(auth);onAuthStateChanged(auth,u=>{if(u){showDashboard();render();loadOrders()}else showLogin()});
async function getProducts(){const snap=await getDocs(collection(db,'products'));products=snap.docs.map(d=>({id:d.id,...d.data()}));products.sort((a,b)=>String(a.name||'').localeCompare(String(b.name||'')))}
function discountOf(x){const old=Number(x.old||0),price=Number(x.price||0);return Number(x.discount)>0?Math.round(Number(x.discount)):(old>price?Math.round((1-price/old)*100):0)}function escapeHtml(v){return String(v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
async function render(){try{await getProducts();$('pc').textContent=products.length;$('table').innerHTML=products.map(x=>{const d=discountOf(x);return `<tr><td>${x.image?`<img class="product-thumb" src="${x.image}" alt="">`:`<span class="product-thumb emoji">${x.emoji||'🧵'}</span>`}</td><td><b>${escapeHtml(x.name||'')}</b>${x.offer?`<small class="offer-text">${escapeHtml(x.offer)}</small>`:''}</td><td>${escapeHtml(x.category||'')}</td><td><b>${money(x.price)}</b>${x.old?`<del>${money(x.old)}</del>`:''}</td><td>${d?`<span class="discount">${d}% OFF</span>`:'—'}</td><td class="actions"><button class="edit" onclick="editProduct('${x.id}')">Edit</button><button class="del" onclick="del('${x.id}')">Delete</button></td></tr>`}).join('')||'<tr><td colspan="6">No products yet.</td></tr>'}catch(e){console.error(e);$('table').innerHTML='<tr><td colspan="6">Could not load products.</td></tr>'}}
window.openForm=()=>{editingId=null;oldImage='';$('formTitle').textContent='Add Product';['name','price','old','discount','offer'].forEach(id=>$(id).value='');$('category').value='Aronai';$('preview').src='';$('photo').value='';$('formError').textContent='';$('modal').classList.add('show')};window.editProduct=id=>{const x=products.find(p=>p.id===id);if(!x)return;editingId=id;oldImage=x.image||'';$('formTitle').textContent='Edit Product';$('name').value=x.name||'';$('category').value=x.category||'Aronai';$('price').value=x.price||'';$('old').value=x.old||'';$('discount').value=x.discount||discountOf(x)||'';$('offer').value=x.offer||'';$('preview').src=oldImage;$('photo').value='';$('formError').textContent='';$('modal').classList.add('show')};window.closeForm=()=>{$('modal').classList.remove('show');$('formError').textContent=''};window.preview=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{$('preview').src=r.result};r.readAsDataURL(f)};
window.saveProduct=async()=>{const n=$('name').value.trim(),cat=$('category').value,pr=+$('price').value,old=+$('old').value||0,discount=Math.max(0,Math.min(99,+$('discount').value||0)),offer=$('offer').value.trim(),f=$('photo').files[0];if(!n||!pr)return $('formError').textContent='Product name and selling price are required.';$('formError').textContent='Saving...';try{let image=oldImage;if(f){const path='products/'+Date.now()+'-'+f.name.replace(/[^a-zA-Z0-9._-]/g,'_'),sref=ref(storage,path);await uploadBytes(sref,f);image=await getDownloadURL(sref)}const data={name:n,category:cat,price:pr,old,discount,offer,image,emoji:'🧵',updatedAt:new Date()};if(editingId)await updateDoc(doc(db,'products',editingId),data);else await addDoc(collection(db,'products'),{...data,createdAt:new Date()});closeForm();await render();alert(editingId?'Product updated successfully.':'Product added and published.')}catch(e){console.error(e);$('formError').textContent='Could not save product: '+e.message}};
window.del=async id=>{if(!confirm('Delete this product?'))return;try{await deleteDoc(doc(db,'products',id));await render()}catch(e){alert('Delete failed: '+e.message)}};
async function loadOrders(){try{const q=query(collection(db,'orders'),orderBy('createdAt','desc'),limit(50)),snap=await getDocs(q);$('oc').textContent=snap.size;$('ordersTable').innerHTML=snap.docs.map(d=>{const x=d.data();return `<tr><td>${d.id.slice(0,8)}...</td><td><b>${escapeHtml(x.customerName||'')}</b><small>${escapeHtml(x.phone||'')}</small></td><td>${money(x.total)}</td><td>${escapeHtml(x.paymentMethod||'')}</td><td><span class="status">${escapeHtml(x.status||'pending')}</span></td></tr>`}).join('')||'<tr><td colspan="5">No orders yet.</td></tr>'}catch(e){$('ordersTable').innerHTML='<tr><td colspan="5">Orders unavailable.</td></tr>'}}
