import { initializeApp } from "https://www.gstatic.com/firebasejs/12.0.0/firebase-app.js";
import { getFirestore, collection, getDocs, addDoc, serverTimestamp } from "https://www.gstatic.com/firebasejs/12.0.0/firebase-firestore.js";
import { firebaseConfig, RAZORPAY_KEY_ID } from "./firebase-config.js";
const app=initializeApp(firebaseConfig),db=getFirestore(app);
const defaultProducts=[{id:1,name:'Traditional Bodo Aronai',category:'Aronai',price:1299,old:1599,emoji:'🧣'},{id:2,name:'Bodo Dokhona',category:'Dokhona',price:1199,old:1499,emoji:'🥻'},{id:3,name:'Bodo Stole',category:'Stole',price:699,old:899,emoji:'🧵'},{id:4,name:'Dress Material Set',category:'Dress Material',price:1499,old:1799,emoji:'👗'},{id:5,name:'Handmade Bodo Bag',category:'Accessories',price:899,old:1099,emoji:'👜'},{id:6,name:'Aronai Muffler',category:'Aronai',price:599,old:799,emoji:'🧣'},{id:7,name:'Bodo Traditional Scarf',category:'Stole',price:749,old:999,emoji:'🧣'},{id:8,name:'Handwoven Gift Set',category:'New Arrivals',price:999,old:1299,emoji:'🎁'}];
let products=[],c=JSON.parse(localStorage.getItem('ms_cart')||'[]'),activeCategory='';
const save=()=>localStorage.setItem('ms_cart',JSON.stringify(c)),money=n=>'₹'+Number(n||0).toLocaleString('en-IN',{minimumFractionDigits:2,maximumFractionDigits:2}),esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function discountOf(p){const old=Number(p.old||0),price=Number(p.price||0);return Number(p.discount)>0?Math.round(Number(p.discount)):(old>price?Math.round((1-price/old)*100):0)}
async function loadProducts(){try{const snap=await getDocs(collection(db,'products'));products=snap.docs.map(d=>({id:d.id,...d.data()}))}catch(e){console.warn('Firebase products unavailable:',e)}if(!products.length)products=defaultProducts;render();update()}
function render(){const q=(document.getElementById('search').value||'').toLowerCase().trim(),list=products.filter(p=>(!activeCategory||p.category===activeCategory)&&(!q||String(p.name||'').toLowerCase().includes(q)||String(p.category||'').toLowerCase().includes(q)));document.getElementById('grid').innerHTML=list.length?list.map(p=>{const d=discountOf(p);return `<article class="card"><div class="photo">${p.image?`<img src="${esc(p.image)}" alt="${esc(p.name)}">`:`<span class="product-art">${p.emoji||'🧵'}</span>`}${d?`<span class="discount-badge">${d}% OFF</span>`:''}${p.offer?`<span class="offer-badge">${esc(p.offer)}</span>`:''}</div><div class="info"><h3>${esc(p.name)}</h3><div class="rating">★★★★★ <span>(12)</span></div><p class="price">${money(p.price)} ${p.old?`<span class="old">${money(p.old)}</span>`:''}</p>${p.offer?`<small class="card-offer">🎁 ${esc(p.offer)}</small>`:''}<button class="add" onclick="add('${String(p.id).replace(/'/g,"\\'")}')">Add to Cart</button></div></article>`}).join(''):'<p style="grid-column:1/-1;text-align:center;padding:40px">No products found.</p>'}
window.filterCategory=cat=>{activeCategory=cat;render()};window.clearCategory=()=>{activeCategory='';document.getElementById('search').value='';render()};window.add=id=>{const p=products.find(x=>String(x.id)===String(id));if(p){c.push(p);save();update();window.cart(true)}};
function update(){document.getElementById('count').textContent=c.length;document.getElementById('items').innerHTML=c.length?c.map((p,i)=>`<div class="row">${p.image?`<img class="row-thumb" src="${esc(p.image)}" alt="">`:`<span class="row-thumb" style="display:grid;place-items:center;font-size:28px">${p.emoji||'🧵'}</span>`}<div><b>${esc(p.name)}</b><br>${money(p.price)}<br><button onclick="removeItem(${i})">Remove</button></div></div>`).join(''):'<p>Your cart is empty.</p>';document.getElementById('total').textContent='Total: '+money(c.reduce((s,p)=>s+Number(p.price||0),0))}
window.removeItem=i=>{c.splice(i,1);save();update()};window.cart=(openOnly=false)=>{const d=document.getElementById('drawer'),s=document.getElementById('shade');if(openOnly||!d.classList.contains('open')){d.classList.add('open');s.classList.add('show')}else{d.classList.remove('open');s.classList.remove('show')}update()};
async function loadRazorpay(){if(window.Razorpay)return true;await new Promise((resolve,reject)=>{const s=document.createElement('script');s.src='https://checkout.razorpay.com/v1/checkout.js';s.onload=resolve;s.onerror=reject;document.head.appendChild(s)});return !!window.Razorpay}
async function saveOrder(data){const ref=await addDoc(collection(db,'orders'),{...data,createdAt:serverTimestamp()});return ref.id}
window.checkout=async()=>{if(!c.length)return alert('Your cart is empty.');const total=c.reduce((s,p)=>s+Number(p.price||0),0),name=prompt('Customer name');if(!name)return;const phone=prompt('Phone number');if(!phone)return;const address=prompt('Delivery address');if(!address)return;const online=confirm('OK = Pay Online\nCancel = Cash on Delivery');if(!online){try{const id=await saveOrder({customerName:name,phone,address,items:c.map(p=>({id:p.id,name:p.name,price:p.price})),total,paymentMethod:'COD',status:'pending'});c=[];save();update();alert('Order placed successfully! Order ID: '+id);window.cart()}catch(e){console.error(e);alert('Order save failed. Please check Firebase Firestore setup.')}return}if(!RAZORPAY_KEY_ID)return alert('Online payment is not configured yet. Add your Razorpay Key ID in firebase-config.js, then deploy again.');try{await loadRazorpay();const options={key:RAZORPAY_KEY_ID,amount:Math.round(total*100),currency:'INR',name:'Minakshi Aronai Shop',description:'Online order',prefill:{name,contact:phone},notes:{address},handler:async response=>{try{const id=await saveOrder({customerName:name,phone,address,items:c.map(p=>({id:p.id,name:p.name,price:p.price})),total,paymentMethod:'Razorpay',paymentId:response.razorpay_payment_id,status:'paid'});c=[];save();update();alert('Payment successful! Order ID: '+id);window.cart()}catch(e){alert('Payment succeeded, but order saving failed. Payment ID: '+response.razorpay_payment_id)}}};new window.Razorpay(options).open()}catch(e){console.error(e);alert('Unable to open online payment. Please try again or choose Cash on Delivery.')}};
loadProducts();